/*

ResourceLoaderAware接口实现类的实例将获得一个ResourceLoader的引用，
ResourceLoaderAware接口也提供了一个setResourceLoader()方法，
该方法将由Spring容器负责调用，Spring容器会将一个ResourceLoader对象作为该方法的参数传入。

如果把实现ResourceLoaderAware接口的Bean类部署在Spring容器中，Spring容器会将自身当成ResourceLoader作为setResourceLoader()方法的参数传入。
由于ApplicationContext的实现类都实现了ResourceLoader接口，Spring容器自身完全可作为ResorceLoader使用。

 */
package online.superh.ResourceLoaderAware;


